- hosts: all
  vars:
    dotfiles_dir: "$HOME/dotfiles"
    home_dir: "$HOME"
    config_dir: "$HOME/.config"

  tasks:
    - name: Create config folder
      file:
        path: "{{ config_dir }}"
        state: directory

    - name: Find .config files
      find:
        paths: "{{ dotfiles_dir }}/config"
        recurse: no
        file_type: any
        hidden: yes
        excludes:
          - '.DS_Store'
          - '.git'
          - 'powerlevel10k'
          - 'zsh'
      register: dot_config

    - name: Link .config items
      file:
        src: "{{ item.path }}"
        dest: "{{ config_dir }}/{{item.path | basename}}"
        state: link
      loop: "{{ dot_config.files }}"
      loop_control:
        label: "{{ config_dir }}/{{item.path | basename}}"

    - name: Find zsh files
      find:
        paths: "{{ dotfiles_dir }}/config/zsh"
        recurse: no
        file_type: any
        hidden: yes
        excludes:
          - '.DS_Store'
          - '.git'
      register: zsh_config

    - name: Link zsh items
      file:
        src: "{{ item.path }}"
        dest: "{{ home_dir }}/{{item.path | basename}}"
        state: link
      loop: "{{ zsh_config.files }}"
      loop_control:
        label: "{{ home_dir }}/{{item.path | basename}}"

    - name: Link powerlevel10k
      file:
        src: "{{ dotfiles_dir }}/config/powerlevel10k/.p10k.zsh"
        dest: "{{ home_dir }}/.p10k.zsh"
        state: link

    - name: Link nvim
      file:
        src: "{{ dotfiles_dir }}/nvim"
        dest: "{{ config_dir }}/nvim"
        state: link

    - name: Link scripts
      file:
        src: "{{ dotfiles_dir }}/scripts"
        dest: "{{ home_dir }}/.local/scripts"
        state: link

    - name: Link Hammerspoon
      file:
        src: "{{ dotfiles_dir }}/hammerspoon"
        dest: "{{ home_dir }}/.hammerspoon"
        state: link

