git:
  paging:
    useConfig: false
    colorArg: always
    pager: delta --paging=never
gui:
  showIcons: true
  theme:
    defaultFgColor:
      - "#2C363C"
    activeBorderColor:
      - ""
      - bold
    inactiveBorderColor:
      - ""
    selectedLineBgColor:
      - "#CBD9E3"
    selectedRangeBgColor:
      - "#CBD9E3"
os:
  editCommand: "edit-nvim-lazygit.sh"
  editCommandTemplate: "{{editor}} {{filename}} {{line}}"
