git:
  paging:
    useConfig: false
    colorArg: "always"
    pager: "delta --paging=never"
gui:
  showIcons: true
  theme:
    selectedLineBgColor:
      - "#dfdad9"
    selectedRangeBgColor:
      - "#dfdad9"
    activeBorderColor:
      - "#286983"
      - "bold"
    inactiveBorderColor:
      - "#dfdad9"
    defaultFgColor:
      - "#575279"
os:
  editCommand: "edit-nvim-lazygit.sh"
  editCommandTemplate: "{{editor}} {{filename}} {{line}}"
