git:
  paging:
    colorArg: always
    pager: diff-so-fancy
gui:
  showIcons: true
  theme:
    defaultFgColor:
      - "#c8d3f5"
    activeBorderColor:
      - "#82aaff"
      - bold
    inactiveBorderColor:
      - "#2f334d"
customCommands:
  - key: "W"
    prompts:
      - type: "input"
        title: "Commit"
        initialValue: ""
    command: git commit -m "{{index .PromptResponses 0}}" --no-verify
    context: "global"
    subprocess: true
    description: "git commit ignoring pre-commit hook (custom)"
os:
  editCommand: 'open_in_neovim.sh'
  editCommandTemplate: '{{editor}} {{filename}} {{line}}'
