git:
  paging:
    useConfig: false
    colorArg: always
    pager: delta --paging=never
gui:
  showIcons: true
  theme:
    defaultFgColor:
      - "#555555"
    activeBorderColor:
      - ""
      - bold
    inactiveBorderColor:
      - ""
    selectedLineBgColor:
      - "#CCCCCC"
    selectedRangeBgColor:
      - "#CCCCCC"
customCommands:
  - key: "W"
    prompts:
      - type: "input"
        title: "Commit"
        initialValue: ""
    command: git commit -m "{{index .PromptResponses 0}}" --no-verify
    context: "global"
    subprocess: true
    description: "git commit ignoring pre-commit hook (custom)"
os:
  editCommand: 'edit-nvim-lazygit.sh'
  editCommandTemplate: '{{editor}} {{filename}} {{line}}'
