git:
  paging:
    colorArg: always
    pager: diff-so-fancy
gui:
  showIcons: true
  theme:
    defaultFgColor:
      - "#3d2b5a"
    activeBorderColor:
      - "#2848a9"
      - bold
    inactiveBorderColor:
      - "#aab0ad"
    selectedLineBgColor:
      - "#e7d2be"
    selectedRangeBgColor:
      - "#e7d2be"
keybinding:
  universal:
    quit: '<c-g>'
customCommands:
  - key: "W"
    prompts:
      - type: "input"
        title: "Commit"
        initialValue: ""
    command: git commit -m "{{index .PromptResponses 0}}" --no-verify
    context: "global"
    subprocess: true
    description: "git commit ignoring pre-commit hook (custom)"
# os:
#   editCommand: 'nvim --server $NVIM --remote'
#   editCommandTemplate: "{{editor}} {{filename}}:{{line}}"
os:
  editCommand: 'lazygit_edit_in_nvim.sh'
  editCommandTemplate: '{{editor}} {{filename}} {{line}}'
