git:
  paging:
    colorArg: always
    pager: diff-so-fancy
gui:
  showIcons: true
  theme:
    lightTheme: false
customCommands:
  - key: "w"
    prompts:
      - type: "input"
        title: "Commit"
        initialValue: ""
    command: git commit -m "{{index .PromptResponses 0}}" --no-verify
    context: "global"
    subprocess: true
    description: "git commit ignoring pre-commit hook (custom)"
